# https://developers.cloudflare.com/pages/functions/wrangler-configuration
d1_databases = [
	{ binding = "DB", database_id = "db-local", database_name = "db-local", preview_database_id = "DB" },
]

[env.staging]
d1_databases = [
	{ binding = "DB", database_id = "<your staging DB ID here>", database_name = "db-staging" },
]

[env.production]
d1_databases = [
	{ binding = "DB", database_id = "<your production DB ID here>", database_name = "db-production" },
]
